import type { QuoteRow } from "./quoteTypes";

export const STATIC_KOREAN_QUOTES: QuoteRow[] = [
  {
    quoteKo: "백성을 위하는 마음이 곧 하늘의 뜻이다.",
    quoteEn: "A heart for the people is the will of Heaven.",
    author: "정조",
    authorEn: "",
    lifespan: "1752–1800",
    achievements: "조선 22대 임금으로 규장각·초계문신 등을 두어 문치를 강화하고 수원 화성 등을 이끔.\n탕평책과 농정 개혁으로 백성을 위한 통치를 지향함.",
  },
  {
    quoteKo: "학문에 있어 근본은 성(性)이요, 공부의 요체는 마음을 바로잡는 데 있다.",
    quoteEn: "In learning, human nature is the root; the essence of study lies in rectifying the mind.",
    author: "조광조",
    authorEn: "",
    lifespan: "1482–1519",
    achievements: "중종반정을 주도한 조선 전기 문신으로 성리학과 경세치용을 강조함.\n《불씨잡변》 등으로 개혁적 성리학 논의를 펼침.",
  },
  {
    quoteKo: "나라의 근본은 농사이니, 백성이 배불리 먹는 것이 첫째다.",
    quoteEn: "The root of the nation is farming; feeding the people comes first.",
    author: "정약용",
    authorEn: "",
    lifespan: "1762–1836",
    achievements: "다산으로 불리며 실학의 거두로 경세제민론을 집대성함.\n《목민심서》 등은 지방관의 책임과 백성 돌봄을 역설함.",
  },
  {
    quoteKo: "글은 사람의 마음을 비추는 거울이니, 글을 닦는 것은 곧 마음을 닦는 일이다.",
    quoteEn: "Writing mirrors the heart; to polish one's writing is to polish one's mind.",
    author: "김정희",
    authorEn: "",
    lifespan: "1786–1856",
    achievements: "추사체와 세한화로 조선 후기 서예·문인화의 새 지평을 염.\n청나라와 교류하며 고증학적 학풍을 넓힘.",
  },
  {
    quoteKo: "의리를 지키는 것이 곧 나라를 지키는 길이다.",
    quoteEn: "Keeping faith and duty is the way to defend the nation.",
    author: "곽재유",
    authorEn: "",
    lifespan: "1552–1617",
    achievements: "임진왜란 때 의병을 일으켜 호남 방어에 기여한 호국장수로 알려짐.\n전라감사 등으로 백성을 위한 정치를 펼침.",
  },
  {
    quoteKo: "바다를 건너야 산이 보이듯, 어려움을 겪어야 사람의 참됨이 드러난다.",
    quoteEn: "As mountains appear only after crossing the sea, a person's truth shows only through hardship.",
    author: "허준",
    authorEn: "",
    lifespan: "1539–1615",
    achievements: "동의보감을 편찬해 한의학과 약재를 체계화한 조선 중기 의학자임.\n왕실과 민간 의료에 두루 관여하며 실용 의서를 남김.",
  },
  {
    quoteKo: "강을 건너 국경을 다툴 때, 말보다 먼저 붓을 들어야 한다.",
    quoteEn: "When rivers and borders are disputed, take up the brush before the sword.",
    author: "서희",
    authorEn: "",
    lifespan: "942–998",
    achievements: "고려 초 외교·학자로 거란과의 강동 6주 영토 분쟁에서 담판을 이끔.\n《강동입지도》 등 지리 인식을 바탕으로 국익을 지킴.",
  },
  {
    quoteKo: "하늘의 이치를 측량하고 땅의 이치를 살핀다.",
    quoteEn: "Measure the principles of Heaven and examine those of Earth.",
    author: "장영실",
    authorEn: "",
    lifespan: "1390경–1450경",
    achievements: "조선 전기 천문·측후 기구를 제작한 과학기술자로 혼천의·측우기 등을 이끔.\n세종대 과학 정책의 중심 인물로 기록됨.",
  },
  {
    quoteKo: "글에는 정(正)이 있어야 하고, 사람에게는 직(直)이 있어야 한다.",
    quoteEn: "Writing must have correctness; a person must have uprightness.",
    author: "이익",
    authorEn: "",
    lifespan: "1681–1763",
    achievements: "성호학파의 거두로 북학론과 실용 학문을 널리 논함.\n《성호사설》 등으로 일상과 제도의 이치를 탐구함.",
  },
  {
    quoteKo: "역사는 백성의 삶이니, 백성 없는 역사는 없다.",
    quoteEn: "History is the life of the people; there is no history without the people.",
    author: "신채호",
    authorEn: "",
    lifespan: "1880–1936",
    achievements: "근대 민족사학의 선구자로 《조선상고사》 등을 저술함.\n일제 감시 속에서도 민족 주체성을 역설한 지식인으로 기억됨.",
  },
  {
    quoteKo: "진실한 시는 피와 눈물로 쓰인다.",
    quoteEn: "True poetry is written with blood and tears.",
    author: "김소월",
    authorEn: "",
    lifespan: "1902–1934",
    achievements: "민요체 시로 한국 현대시에 서정의 새 결을 열었음.\n《진달래꽃》 등은 애절한 이별과 향수를 노래함.",
  },
  {
    quoteKo: "살아 있는 동안 조국을 위해 쓰다 가겠다.",
    quoteEn: "While I live, I will spend myself for the homeland.",
    author: "김구",
    authorEn: "",
    lifespan: "1876–1949",
    achievements: "대한민국 임시정부를 이끈 독립운동가로 광복과 통일을 염원함.\n《백범일지》에 독립과 민족교육에 대한 신념이 담겨 있음.",
  },
  {
    quoteKo: "새로운 길은 남이 가지 않은 곳에 있다.",
    quoteEn: "New paths lie where others have not gone.",
    author: "박두진",
    authorEn: "",
    lifespan: "1916–1992",
    achievements: "농촌과 자연을 노래한 시인으로 민족 분단과 삶의 근원을 성찰함.\n《청룡강》 등으로 한국 전후 시의 한 흐름을 대표함.",
  },
  {
    quoteKo: "시는 말이 아니라 숨이고, 숨은 삶의 자리다.",
    quoteEn: "Poetry is not words but breath, and breath is the place of life.",
    author: "서정주",
    authorEn: "",
    lifespan: "1915–2000",
    achievements: "한국 현대시의 거장으로 자연과 역사·존재를 서정적으로 형상화함.\n《국화와 찻잔》 등 다수의 시집으로 문학상을 수상함.",
  },
  {
    quoteKo: "여성도 배우고 일하며 스스로를 세울 수 있다.",
    quoteEn: "Women, too, can learn, work, and stand on their own.",
    author: "나혜석",
    authorEn: "",
    lifespan: "1896–1948",
    achievements: "근대 한국 최초의 여성 서양화가이자 계몽운동에 참여함.\n《이상적 부인》 등으로 신여성상과 예술의 결합을 모색함.",
  },
  {
    quoteKo: "글은 나라의 기둥이요, 말은 백성의 다리다.",
    quoteEn: "Writing is the pillar of the state; speech is the legs of the people.",
    author: "최치원",
    authorEn: "",
    lifespan: "857–?",
    achievements: "신라 말·고려 초의 문장가·학자로 과거제를 주장한 《시무책》을 올림.\n한문 문예와 정치론으로 통일 신라 말기 사회를 비판함.",
  },
  {
    quoteKo: "백성의 목소리가 곧 정치의 거울이다.",
    quoteEn: "The voice of the people is the mirror of politics.",
    author: "유형원",
    authorEn: "",
    lifespan: "1622–1673",
    achievements: "반계로 불리며 조선 후기 실학과 경세사상을 정리함.\n《산대일기》 등에서 농정과 민생을 중시한 통치론을 펼침.",
  },
  {
    quoteKo: "나라를 바로잡으려면 먼저 역사를 바로잡아야 한다.",
    quoteEn: "To set the nation right, one must first set history right.",
    author: "박은식",
    authorEn: "",
    lifespan: "1859–1925",
    achievements: "근대사학과 독립운동을 겸한 지식인으로 《한국통사》 등을 저술함.\n국권 수호와 계몽을 역설한 언론인이기도 함.",
  },
  {
    quoteKo: "바람이 불면 음악이 되고, 마음이 움직이면 시가 된다.",
    quoteEn: "When wind blows, it becomes music; when the heart stirs, it becomes poetry.",
    author: "정지용",
    authorEn: "",
    lifespan: "1902–?",
    achievements: "한국 초기 현대시인으로 상징과 감각의 시어를 실험함.\n《향수》 등은 도시와 향토를 넘나드는 정서로 읽힘.",
  },
  {
    quoteKo: "독립은 하늘이 내린 권리이며, 민족 모두의 의무다.",
    quoteEn: "Independence is a right granted by Heaven and a duty of the whole nation.",
    author: "안창호",
    authorEn: "",
    lifespan: "1878–1938",
    achievements: "교육·계몽과 독립운동을 병행한 지도자로 대한인국민회 등을 이끔.\n해외에서도 독립군 양성과 민족 교육에 힘씀.",
  },
  {
    quoteKo: "글로써 뜻을 전하고 그림으로써 마음을 보인다.",
    quoteEn: "Convey meaning with writing and show the heart with painting.",
    author: "신사임당",
    authorEn: "",
    lifespan: "1504–1551",
    achievements: "조선 중기의 여성 시인·화가로 매화·초충 등을 그림.\n율곡 이이의 어머니로도 알려지며 여성 문예의 모범으로 전해짐.",
  },
  {
    quoteKo: "백성을 사랑하지 않는 나라는 오래가지 못한다.",
    quoteEn: "A state that does not love its people cannot endure.",
    author: "세종대왕",
    authorEn: "",
    lifespan: "1397–1450",
    achievements: "농서와 역법을 정비하고 악기·천문 기구를 개량하는 등 실용 통치를 펼침.\n한글 창제로 백성의 소통을 넓힌 성군으로 기록됨.",
  },
  {
    quoteKo: "죽음을 두려워 말고, 나라를 두려워하라.",
    quoteEn: "Do not fear death; fear for the nation.",
    author: "이순신",
    authorEn: "",
    lifespan: "1545–1598",
    achievements: "전라좌수군절도사 등으로 임진왜란 전반기부터 수군을 재건함.\n노량해전에서 최후를 맞이하기까지 조선 수군의 상징으로 남음.",
  },
  {
    quoteKo: "배움의 끝은 없고, 덕을 쌓는 일도 끝이 없다.",
    quoteEn: "Learning has no end, nor does the cultivation of virtue.",
    author: "이황",
    authorEn: "",
    lifespan: "1501–1570",
    achievements: "서원 교육과 성리학 경전 연구로 조선 유학의 기틀을 다짐.\n《성학집요》 편찬 등으로 임금과 신료의 학문을 이끔.",
  },
  {
    quoteKo: "지혜는 백성 속에 있고, 정책은 밭과 시장에서 나온다.",
    quoteEn: "Wisdom lies among the people; policy comes from the fields and markets.",
    author: "박지원",
    authorEn: "",
    lifespan: "1737–1805",
    achievements: "연암으로 불리며 북학과 실용 문체로 당대를 풍자함.\n《열하일기》는 청나라 견문을 통해 개혁을 촉구한 기행문학의 걸작임.",
  },
  {
    quoteKo: "별 하나에 추억과 별 하나에 사랑과 별 하나에 쓸쓸함과…",
    quoteEn: "In one star, memory; in one star, love; in one star, loneliness…",
    author: "윤동주",
    authorEn: "",
    lifespan: "1917–1945",
    achievements: "일제 말기 젊은 시인으로 민족어와 서정을 결합함.\n《별 헤는 밤》은 고향과 자아를 성찰하는 시로 널리 암송됨.",
  },
  {
    quoteKo: "죽는 날까지 하늘을 우러러 한 점 부끄없기를…",
    quoteEn: "Until the day I die, not a moment of shame toward heaven…",
    author: "윤동주",
    authorEn: "",
    lifespan: "1917–1945",
    achievements: "일본 유학 시절에도 모국어로 시를 쓰며 민족 정체성을 지킴.\n옥중 시와 유고는 한국 전후 문학의 상징적 텍스트가 됨.",
  },
  {
    quoteKo: "나는 대한의 독립을 위해 죽는 것이 영광이라 생각한다.",
    quoteEn: "I deem it an honor to die for Korea's independence.",
    author: "유관순",
    authorEn: "",
    lifespan: "1900–1920",
    achievements: "3·1 만세운동의 현장을 이끌며 여성·청년의 역할을 보여 줌.\n재판 과정에서도 독립 의지를 굽히지 않음.",
  },
  {
    quoteKo: "십만 양병이 죽을 각오로 나아가니 적군이 물러갈 수밖에 없었다.",
    quoteEn: "A hundred thousand soldiers advanced resolved to die, so the enemy had no choice but to retreat.",
    author: "권율",
    authorEn: "",
    lifespan: "1537–1599",
    achievements: "임진왜란 때 조몬연합군으로 진주성·행주대첩 등에서 활약한 장수임.\n수군과 육군을 오가며 전선을 지킨 호국 인물로 기록됨.",
  },
  {
    quoteKo: "내가 그의 이름을 불러 주기 전에는 그는 다만 하나의 몸짓에 지나지 않았다.",
    quoteEn: "Before I called his name, he was no more than a gesture.",
    author: "김춘수",
    authorEn: "",
    lifespan: "1920–2004",
    achievements: "한국 현대시를 대표하는 시인으로 《풀꽃》 등으로 사물과 이름의 철학을 형상화함.\n전후 세대의 언어 실험과 서정에 지대한 영향을 끼침.",
  },
  {
    quoteKo: "이 몸이 죽고 죽어 일백 번 고쳐 죽어 백골이 진토되어 넋이라도 있고 없고 임 향한 일편단심이야 가실 줄이 있으랴.",
    quoteEn: "Though my body die and die again, a hundred times to dust, could that steadfast heart toward you ever waver?",
    author: "정몽주",
    authorEn: "",
    lifespan: "1337–1392",
    achievements: "고려 말·조선 초의 문신·학자로, 성리학을 받아들이며 조선 건국의 이념적 토대를 마련함.\n《단심가》는 충절과 절의를 상징하는 시로 널리 전함.",
  },
  {
    quoteKo: "필사즉생 필생즉사.",
    quoteEn: "Fight as if to live, and you may live; cling only to life, and you may perish.",
    author: "이순신",
    authorEn: "",
    lifespan: "1545–1598",
    achievements: "임진왜란 때 조선 수군을 이끌며 나라를 구한 무신·제독으로, 《난중일기》에 전술과 심정이 남아 있음.\n명량·한산도 대첩 등 해전사의 상징적 인물로 기억됨.",
  },
  {
    quoteKo: "어리석은 백성이 말하고자 하나 마침내 제 뜻을 펴지 못하는 사람이 많으니, 내가 이를 가엾게 여겨 새로 이십팔 자를 만드니…",
    quoteEn: "Many common people wish to speak yet cannot express themselves; pitying this, I have devised twenty-eight new letters…",
    author: "세종대왕",
    authorEn: "",
    lifespan: "1397–1450",
    achievements: "조선 4대 임금으로 훈민정음(한글) 창제·과학·농학·악학 등을 장려한 성군으로 평가받음.\n백성의 글을 쉽게 배우게 하려는 통치 철학이 《훈민정음》 해례본에 담겨 있음.",
  },
  {
    quoteKo: "공부한 것을 남에게 가르치려면 먼저 스스로의 마음을 바로잡아야 한다.",
    quoteEn: "To teach others what you have learned, you must first set your own mind right.",
    author: "이황",
    authorEn: "",
    lifespan: "1501–1570",
    achievements: "조선 중기 성리학의 거두로 이기론·성즉이야설 등을 체계화함.\n퇴계 서원과 후학 양성을 통해 유학 전통을 굳건히 함.",
  },
  {
    quoteKo: "지키기 어려운 것은 마음이요, 다스리기 어려운 것은 몸이다.",
    quoteEn: "What is hard to keep is the mind; what is hard to govern is the body.",
    author: "이이",
    authorEn: "",
    lifespan: "1536–1584",
    achievements: "율곡으로 불리며 조선 성리학과 실천 윤리를 통합해 논하였음.\n동호문답·성학집요 등으로 군주 교육과 신하의 덕목을 역설함.",
  },
  {
    quoteKo: "죽는 날까지 하늘을 우러러 한 점 부끄없기를, 잎새에 이는 바람에도 괴이어 가는 길을…",
    quoteEn: "Until the day I die, I would lift my face to the sky and not be ashamed; even the wind brushing the leaves would make me start on the path…",
    author: "윤동주",
    authorEn: "",
    lifespan: "1917–1945",
    achievements: "일제강점기 시인으로 민족적 정서와 자기성찰을 노래함.\n《서시》·《별 헤는 밤》 등은 한국 현대시의 정점으로 꼽힘.",
  },
  {
    quoteKo: "님은 갔습니다. 아아, 사랑하는 나의 님은 갔습니다.",
    quoteEn: "You have gone. Ah, my beloved, you have gone.",
    author: "한용운",
    authorEn: "",
    lifespan: "1879–1944",
    achievements: "불교 개혁과 독립운동, 시와 산문으로 근대 한국 문예사상에 큰 족적을 남.\n《님의 침묵》은 자유시 형식과 서정으로 널리 읽힘.",
  },
  {
    quoteKo: "얼어 죽을 말은 하나도 없다.",
    quoteEn: "There isn't a single word that should die frozen on the tongue.",
    author: "방정환",
    authorEn: "",
    lifespan: "1899–1931",
    achievements: "소년·아동 문예운동과 《어린이》 잡지를 이끈 계몽 지식인임.\n어린이를 존중하는 언어와 교육을 강조하며 근대 아동문화의 선구자로 기억됨.",
  },
  {
    quoteKo: "나라가 망하여도 십년이면 번성한다 하였거늘, 오백년 은덕을 입은 백성이 어찌 쉬 죽겠는가.",
    quoteEn: "They say a fallen nation may thrive again in ten years; how could the people, blessed five hundred years, perish so easily?",
    author: "안중근",
    authorEn: "",
    lifespan: "1879–1910",
    achievements: "의병과 독립운동에 참여한 독립운동가로 하얼빈 의거로 알려짐.\n《동양평화론》 등에서 동아시아 평화와 독립의 도리를 역설함.",
  },
  {
    quoteKo: "몸바쳐 나라를 위하고 백성을 위하니, 죽음이 두렵지 않다.",
    quoteEn: "I give myself to the nation and the people; I do not fear death.",
    author: "유관순",
    authorEn: "",
    lifespan: "1900–1920",
    achievements: "3·1 운동을 주도한 독립운동가로, 서울 종로와 천안 아우내 만세시위를 이끔.\n이후 옥중에서도 독립 정신을 호소한 젊은 애국자로 기억됨.",
  },
];

export const SEED_QUOTES = STATIC_KOREAN_QUOTES;
export const FALLBACK_QUOTES = STATIC_KOREAN_QUOTES;
